Make pages and add locales and images
sparcs-kaist/new-ara-app pull request #1
Opened 2022-10-29 10:19 UTC by sangohkim

1. locale 설정을 위한 json 파일을 assets에 만들어놓았습니다.
2. figma 디자인에 사용된 이미지 파일을 svg 형식으로 assets에 저장해놓았습니다.
3. lib 폴더 내에 main.dart, home.dart를 생성해 기본적인 앱 설정을 하였습니다.
4. lib 폴더 내에 상수 저장용 constants 디렉터리를 생성하였습니다.
5. lib 폴더 내에 pages 디렉터리를 생성하고 내부에 세부적인 페이지 소스코드를 작성하였습니다.

2022-10-29 12:28 UTC, sboh1214 requested changes

2022-10-29 12:28 UTC, sboh1214 commented on lib/main.dart
> +  const Locale('en', 'US'),
'en' 'ko' 만 명시해 주는 것이 좋을 것 같습니다.
국가까지 명시해 주면 해당 언어를 사용하는 다른 국가에서는 자동으로 설정이 안될 수 있어요

2022-10-29 12:28 UTC, sboh1214 commented on lib/constants/colors.dart
> +const BACKGROUND_COLOR = Colors.white;
아래 예제 코드와 비슷하게 color 관련 상수값들을 묶어 주는것은 어떨까요?
```
class MyConfig {
  static const String country = 'Mongolia';
  static const String animal = 'horse';
}
```

2022-10-29 12:28 UTC, sangohkim commented
지원 플랫폼에서 windows, macos, linux, web은 제거하였습니다

2022-10-29 12:37 UTC, sangohkim commented on lib/main.dart
> +  const Locale('en', 'US'),
locale 관련 코드 및 파일명에서 국가명(KR, US) 제거했습니다

2022-10-29 12:41 UTC, sangohkim commented on lib/constants/colors.dart
> +const BACKGROUND_COLOR = Colors.white;
좋을 것 같습니다. 그러면 앱에서 필요한 상수들을 저장한 파일을 하나만 만들고 파일 내부에서 클래스를 이용해서 종류별로 나누는 방식으로 할까요?

2022-10-29 14:01 UTC, sboh1214 commented on lib/constants/colors.dart
> +const BACKGROUND_COLOR = Colors.white;
넵 좋습니다!

2022-10-29 14:24 UTC, sangohkim commented on lib/constants/colors.dart
> +const BACKGROUND_COLOR = Colors.white;
변경완료했습니다

2022-10-30 09:01 UTC, sboh1214 approved these changes
LGTM now

2022-10-30 12:29 UTC, merged