Feature/html editor
sparcs-kaist/new-ara-app pull request #15
Opened 2023-10-05 21:49 UTC by skykhs3

기존 html 에디터인 [html_editor_enhaced](https://pub.dev/packages/html_editor_enhanced) 에서 한글 입력 오류가 나서
새로운 html 에디터인 [flutter_quill](https://pub.dev/packages/flutter_quill) 로 교체하려고 합니다.

교체 시 확인 해봐야할 기능은 다음과 같습니다.

1.  새로운 포스트의 글과 그림이 업로드가 되어야함.
2.  게시물을 작성 시; 사진을 추가할 때 첨부파일에 해당 사진도 추가가 되야함 
3.  게시물을 작성 시; 첨부파일 삭제 시 첨부파일이 제대로 삭제가 되어야함.
4.  게시물을 작성 시; 사진의 규격은 html에서 사용자가 지정한 대로 제대로 업로드가 되어야함.

5. 게시물을 수정 시; 사진와 글이 규격을 맞춰서 제대로 불러와져야함
6. 게시물을 수정 시; 새로운 추가한 첨부파일이 반영되어서 올라가야함.
7.  게시물을 수정 시; 새로운 첨부파일과 기존 첨부파일 삭제 시  둘 다 반영 되어야함
8. 게시물 수정 시; 새로 추가한 사진이 반영되어서 올라가야함.
9. 게시물 수정 시; 새로운 사진과 기존 사진이 삭제 시 둘 다 반영 되어야함.

위 9가지 사항들을 프론트 상 화면에서 제대로 반영이 되는 지 확인을 하고, 백엔드에서 요청이 제대로 이뤄졌는지 확인하기 위해 수정한 게시물을 확인 해야합니다.

2023-10-08 14:45 UTC, skykhs3 commented
1 ~ 10번 사항 모두 반영하여 코드 작성 완료했습니다.
그렇지만 개선할 점이 있습니다.
현재 Html를 Delta로 바꾸는 dart 라이브러리가 없기 때문에 Html을 마크다운으로 바꾸고, 마크다운을 Delta로 바꾸었습니다.
하지만 <strong>1234<em>56</em></strong><em>789</em>을Markdown 다운에서 표시할 수 없다는 단점이 있어. 이런 형식은 editor에서 표현을 못하고 있습니다.

2023-10-26 15:26 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +          _htmlToQuillDelta(widget.previousArticle!.content!));
previousArticle이 null인 경우에 대한 처리를 추가해야 할 것 같습니다.

2023-10-26 16:03 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +        width: double.infinity,
Figma 디자인을 보면 Menubar가 화면 좌우와는 떨어져있으므로 width를 double.infinity에서 변경하여야 할 것 같습니다.

2023-10-26 16:12 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +          setState(() {});
setState의 용도 주석 추가 부탁드립니다.

2023-10-26 16:14 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +        style: TextStyle(
const 추가 부탁드립니다.

2023-10-26 16:15 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +        decoration: InputDecoration(
InputDecoration에 const 추가 부탁드립니다.

2023-10-26 16:19 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +          if (isKeyboardVisible && false) {
조건식이 항상 false이니 제거 부탁드립니다.

2023-10-27 10:53 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                                color: Colors.red,
flutter_svg 버전에 1버전대에서 2.0.0+1로 변경됨에 따라 SvgPicture.asset의 color가 deprecated 되었습니다.
```
final Widget svgIcon = SvgPicture.asset(
  assetName,
  colorFilter: ColorFilter.mode(Colors.red, BlendMode.srcIn),
  semanticsLabel: 'A red up arrow'
);
```
위와 같은 형식으로 변경 부탁드립니다.

2023-10-27 11:06 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                                                      color: Colors.black,
위의 flutter_svg comment와 동일한 이유로 color 필드 수정 부탁드립니다.

2023-10-27 11:09 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                                                                    .fileLocalPath!)
해당 코드 시점에서 fileLocalPath가 null인 경우가 있을 수 있나요? !는 null일 경우 바로 에러를 내므로 만약 있다고 판단되시면 !보다는 추가적인 null check 로직을 사용하는 것이 좋을 것 같습니다.

2023-10-27 11:12 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                                                                      .fileLocalPath!)
위의 comment와 동일한 이유로 인해 fileLocalPath가 코드 상의 에러 혹은 시스템 등 외부적인 요인에 의해 null일 경우가 있다고 판단되시는 경우 ! 대신 추가적인 로직으로 처리하는 것이 좋을 것 같습니다.

2023-10-27 11:15 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                                                              .lengthSync())
lengthSync가 FileSystemException을 일으키면 파일 크기를 텍스트로 제대로 표시할 수 없게 될 수 있으므로 나중에 formatBytes에 대한 TODO 처리를 하실 때 try catch를 사용하시는 등의 방법으로 보완 부탁드립니다.

2023-10-27 11:18 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                                                        color:
위의 flutter_svg comment와 동일한 이유로 color 필드 수정 부탁드립니다.

2023-10-27 11:29 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                          _selectedCheckboxes[1] = !_selectedCheckboxes[1]!;
index 1이 어떤 의미인지 주석 추가 부탁드립니다.

2023-10-27 11:30 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                          _selectedCheckboxes[2] = !_selectedCheckboxes[2]!;
위와 비슷한 이유로 index 2의 의미에 대한 주석 추가 부탁드립니다.

2023-10-27 11:30 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                          color: Colors.white,
위의 flutter_svg comment와 동일한 이유로 color 필드 수정 부탁드립니다.

2023-10-27 11:33 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +    Widget _buildRegacy() {
사용하지 않는 메서드로 보이는데 혹시 다른 용도가 있다면 주석으로 설명 추가해주시고 아니라면 제거 부탁드립니다.

2023-10-27 11:40 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                              onTap: () => _pickFile(),
첨부파일에 추가하는 경우에는 image라도 FileType을 Other로 설정하는 것 같습니다. 혹시 첨부파일은 모두 Other로 결정하신 건지 아니면 TODO인 부분인지 궁금합니다.

2023-10-27 11:41 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +  void _deleteImageWithSrc(String src, quill.QuillController controller) {
사용하지 않는 함수로 보이는데 TODO인 부분인가요? 아닌 경우에는 제거 부탁드립니다.

2023-10-27 11:47 UTC, sangohkim requested changes
리뷰 완료하였습니다. comment 되어있는 부분 확인 부탁드리고 flutter analyze등을 이용하여 리빌드가 필요없는 위젯에는 const 모두 추가 부탁드립니다.

2023-10-29 07:33 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +          _htmlToQuillDelta(widget.previousArticle!.content!));
_isEditingPost 라는 변수에 widget.previousArticle이 null이면 false가 되도록 하고 있고, _getPostContent 함수 처음을 보시면 _isEditingPostrrk null 일 경우 함수를 리턴하고 있어, 저 코드가 실행될 때 로직 상으로 previousArticle이 null인 경우는 없습니다.

2023-10-29 07:58 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +                                color: Colors.red,
BlendMode.srcIn 가 무엇을 의미하는 지 공부가 필요할 것 같습니다. 일단 다 BlendMode.srcIn으로 변경하였습니다. @sangohkim

2023-10-29 08:12 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +                                                                    .fileLocalPath!)
```
_attachmentList[index]
                                                          .isNewFile
                                                      ? path.basename(
                                                          _attachmentList[index]
                                                              .fileLocalPath!)
                                                      : _attachmentList[index]
                                                          .fileUrlName,
```
_attachmentList[index].isNewFile은 현재 파일이 로컬에서 추가한 파일이면 true, 클라우드으로 가져온 파일이면 false 입니다. 이미 클라우드에 올라가 있는 사진이라면 다시 업로드할 필요가 없으므로 isNewFile이라는 변수를 통해 관리하고 있습니다.
새로 추가한 파일의 경우 파일의 로컬 파일 명을 띄워주고, 클라우드 사진의 경우 url에서 파일 명을 추출하여 표시하고 있습니다.
쉽게 설명하면 isNewFile true의 경우 fileLocalPath에 파일 이름 정보를 가지고 있고, isNewFile false의 경우 fileUrlName에 파일 이름정보를 가지고 잇습니다.

2023-10-29 08:17 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +                                                                      .fileLocalPath!)
fileLocalPath가 null 경우가 있습니다. 맨 처음 초기화가 되기 전까지는 null 이지만, fetch 받은 정보로 초기화 이후로는 쭉 String 입니다. 단지 `path.basename()` 함수가 String? 이 아닌 String을 요구하기에 컴파일 에러가 나서 !를 붙여준 것입니다.

2023-10-29 08:27 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +                                                              .lengthSync())
```
void _checkAttachmentsValid() {
    // _attachmentList에서 원소를 직접 삭제하기
    for (int i = _attachmentList.length - 1; i >= 0; i--) {
      if (_attachmentList[i].isNewFile) {
        File file = File(_attachmentList[i].fileLocalPath!);
        if (!file.existsSync()) {
          _attachmentList.removeAt(i);
        }
      }
    }
  }
```
이런 함수를 build 함수에서 실행시켜서 file이 유효하지 않을 경우 _attachmentList에서 아예 삭제하도록 로직을 추가햇습니다.

2023-10-29 08:45 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +                              onTap: () => _pickFile(),
```
setState(() {
        _isFileMenuBarSelected = true;
        _attachmentList.add(AttachmentsFormat(
          //TODO: 파일 타입 결정해서 FileType에 추가하기, svg파일도 추가하기.
          fileType: FileType.Other,
          isNewFile: true,
          fileLocalPath: file.path,
        ));
      });
      
``` 
todo 추가했습니다. 해당하는 svg도 아직 없어서 todo로 남겨둔 부분이였습니다.

2023-10-29 08:45 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +    Widget _buildRegacy() {
삭제했습니다.

2023-10-29 10:19 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +    Widget buildEdior() {
buildEditor로 명명하시려다가 오타가 난 듯합니다.

2023-10-29 14:48 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +    Widget buildEdior() {
변경 완료 했습니다.

2023-10-30 02:27 UTC, sangohkim approved these changes

2023-10-30 05:29 UTC, merged