Feature/post write page/anonymous
sparcs-kaist/new-ara-app pull request #18
Opened 2023-11-04 12:41 UTC by skykhs3

1.  Feat: 익명 기능 구현
2. Fix: 에디터의 내용이 빈 칸일 시 업로드 버튼 비활성화
3. Fix: 메뉴바 오류 수정 (맨 처음 게시물 작성 시 "말머리 없음" -> "말머리를 선택하세요")

2023-11-04 12:44 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> -          ),
필요없는 기능이라 삭제 했습니다.

2023-11-04 15:17 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +                              color: Colors.white,
colorFilter 필드로 수정 부탁드립니다.

2023-11-04 15:19 UTC, sangohkim commented on lib/pages/post_write_page.dart
>    bool _isLoading = true;
// 주석을 사용하니 vscode에서 변수 설명을 감지하지 못하는 것 같습니다. // 주석 대신 /// 주석으로 변경 부탁드립니다.

2023-11-04 15:19 UTC, sangohkim commented on lib/pages/post_write_page.dart
>    bool _isUploadingPost = false;
// 주석에서 /// 주석으로 변경 부탁드립니다.

2023-11-04 15:19 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +  bool _hasEditorText = false;
/// 주석으로 변경해주시고 설명 추가 부탁드립니다.

2023-11-04 15:31 UTC, sangohkim commented on lib/pages/post_write_page.dart
>      return Scaffold(
build의 시작에서 if (_isLoading) return const LoadingIndicator(); 구문을 이용하는 것보다 return 부분에 삼항연산자를 이용해서 구현하는 것이 더 가독성이 높지 않을까요?

2023-11-04 15:55 UTC, sangohkim commented on lib/pages/post_write_page.dart
> +          setState(() {});
현재 onChanged의 목적은 canIupload를 업데이트하는 것 같습니다. 성능의 차이는 없겠으나
```
setState(() {
    canIUpload = .....;
});
```
위와 같이 수정하는 것이 코드 의미파악을 더 쉽게 해 줄 것 같은데 어떠신가요?

2023-11-04 16:06 UTC, sangohkim requested changes
리뷰 완료하였습니다. comment 추가가 안되는 줄에 대해 수정 요청할 사항들이 있어 아래에 적어놓았습니다.
1. late TargetPlatform? platform; 변수 설명 주석 추가하기
2. keyboardSubscription 변수는 더 이상 사용하지 않는 것 같아 제거 부탁드립니다.
3. 212번째, 1162번째 줄 부근의 dio요청에서는 try-catch 문이 DioException을 사용하지 않는 것 같아 수정 부탁드립니다.

2023-11-04 17:51 UTC, skykhs3 commented on lib/pages/post_write_page.dart
> +          setState(() {});
```
Widget build(BuildContext context) {
    // if (_isLoading) return const LoadingIndicator();

    var userProvider = context.watch<UserProvider>();

    /// 게시물 업로드 가능한지 확인
    /// TODO: 업로드 로딩 인디케이터 추가하기
    bool canIupload = _titleController.text != '' &&
        _chosenBoardValue!.id != -1 &&
        _isUploadingPost == false &&
        _hasEditorText;
```

canIupload 변수는 빌드 함수 안에 있는 변수로, 여러 조건을 따져 자동으로 결정되는 거라 canIUpload를 임의로 어떤 값으로는 못 바꿀 것 같습니다.

2023-11-06 00:55 UTC, sangohkim approved these changes
LGTM

2023-11-06 02:48 UTC, merged