Feat(global_key.dart): Custom RefreshIndicator 생성
sparcs-kaist/new-ara-app pull request #202
Opened 2024-05-20 16:44 UTC by thomaskim1130

refreshIndicatorKey (gloabl_key.dart 내부에도 저장) 를 생성해 trigger를 위해 pull down해야 하는 거리를 조정함 (50 -> 20).

위를 main_page, user_page, post_list_show_page 에만 적용함.

## Overview

로딩을 위해 pull down하는 거리 감소. 편의성 증진
## Changes

- refreshIndicator.adaptive()를 ScrollNotification 클래스를 활용해 custom화 함. 
- 기존 pull down 50(변경 불가) 에서 20으로 조정.
- main_page.dart, post_list_show_page.dart, user_page.dart에 적용
## Implementaion Method

- global_key.dart에 refreshIndicatorKey 추가
## After Changes

## Related Issues

## Rollback Scenario

## TODO

- user_view_page.dart 에도 적용.
- refreshIndicator 다수 중복. Wrapper 함수 제작?

2024-07-17 16:09 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +                                      parent: BouncingScrollPhysics()),
원래 안드로이드 기종에서는 바운싱 효과가 없는게 기본설정이어서 parent: BouncingScrollPhysics()를 설정해주게 되면 바운싱 효과가 나타나게됩니다. 문제가 될 부분은 전혀 없는데 혹시 의도하신 부분인지가 궁금합니다!

2024-07-18 04:08 UTC, sangohkim commented on lib/utils/refresh_indicator.dart
> +import 'package:flutter/material.dart';
위젯을 생성하는 기능이니 utils 보다는 widgets 디렉터리에 위치시키는게 좋을것 같습니다.

2024-07-18 04:11 UTC, sangohkim commented on lib/utils/global_key.dart
> +final GlobalKey<RefreshIndicatorState> refreshIndicatorKey =
이 파일에 있는 refreshIndicatorKey는 UserPage에서만 사용하고, 다른 페이지에서는 페이지 내부에서 _refreshIndicatorKey를 사용하는 방식으로 구현되어 있는데 사용방식의 통일이 필요할 것 같습니다.

2024-07-18 04:16 UTC, sangohkim commented on lib/pages/user_page.dart
> +    return NotificationListener<ScrollNotification>(
customRefreshIndicator가 이미 NotificationListener를 반환하는 형태로 구현되어 있어 수정이 필요할 것 같습니다. customRefreshIndicator의 적용방식이 UserPage에서만 조금씩다른 것 같은데(global key 사용 및 현재 부분에서) 혹시 다르게 구현하신 이유가 있을까요?

2024-07-18 04:26 UTC, sangohkim requested changes
RefreshIndicator 직접 만드시느라 수고많으셨습니다! 리뷰 완료하였고 코멘트 달린 부분들 한번 봐주시면 될 것 같아요. 
그리고 한가지 수정해야할 부분이 보이는데 PostListShowPage, NotificationPage에서 pull down을 조금만 하면 의도했던 방식으로 리프레시가 진행되지만 pull down을 많이 하게되는 경우 페이지 중앙의 로딩인디케이터(저희가 저번에 페이지가 처음 로드될때만 보여주는걸로 한 부분)이 다시 나타나는 현상을 확인하였습니다. 저도 시간날때 원인을 파악해볼테니 이 부분도 확인부탁드립니다.
- iOS, android 모두에서 확인되었습니다

2024-11-14 18:37 UTC, closed without merging

2024-11-14 18:38 UTC, thomaskim1130 commented
Closed for now (outdated, continued in https://github.com/sparcs-kaist/new-ara-app/pull/246)