Create CustomRefreshIndicator - edited for upgrade
sparcs-kaist/new-ara-app pull request #246
Opened 2024-11-14 18:37 UTC by thomaskim1130

## Overview

로딩을 위해 pull down하는 거리 감소. 편의성 증진
## Changes

- refreshIndicator.adaptive()를 ScrollNotification 클래스를 활용해 custom화 함. 
- 기존 pull down 50(변경 불가) 에서 30으로 조정. (변경 가능)
- main_page.dart, post_list_show_page.dart, user_page.dart, post_view_page 등 페이지에 적용
## Implementaion Method

- utils/refresh_indicator.dart를 추가하여 메소드 customRefreshIndicator 생성
## After Changes

- scrollDownLength를 customize할 수 있음
- radius, color, 애니메이션 딜레이 등도 모두 customize 가능
- refresh 함수를 호출하는 중 중복되지 않음
## Related Issues

- LoadingIndicator(화면 중앙)와 동시에 나타나는 현상이 발생하기도 함
## Rollback Scenario

1. customRefreshIndicator 대신 refreshIndicator.adaptive 사용
2. AlwaysScrollablePhysics의 parent 변경하기
## TODO

- user_view_page.dart 에도 적용. (DONE)
- refreshIndicator 다수 중복. Wrapper 함수 제작? (DONE)

2024-11-15 09:49 UTC, thomaskim1130 commented
> ## Overview
> 로딩을 위해 pull down하는 거리 감소. 편의성 증진
> 
> ## Changes
> * refreshIndicator.adaptive()를 ScrollNotification 클래스를 활용해 custom화 함.
> * 기존 pull down 50(변경 불가) 에서 30으로 조정. (변경 가능)
> * main_page.dart, post_list_show_page.dart, user_page.dart, post_view_page 등 페이지에 적용
> 
> ## Implementaion Method
> * utils/refresh_indicator.dart를 추가하여 메소드 customRefreshIndicator 생성
> 
> ## After Changes
> * scrollDownLength를 customize할 수 있음
> * radius, color, 애니메이션 딜레이 등도 모두 customize 가능
> * onRefresh 함수를 호출하는 중 중복되지 않음
> 
> ## Related Issues
> * LoadingIndicator(화면 중앙)와 동시에 나타나는 현상이 발생하기도 함
> 
> ## Rollback Scenario
> 1. customRefreshIndicator 대신 refreshIndicator.adaptive 사용
> 2. AlwaysScrollablePhysics의 parent 변경하기
> 
> ## TODO
> * user_view_page.dart 에도 적용. (DONE)
> * refreshIndicator 다수 중복. Wrapper 함수 제작? (DONE)
> * Dark Mode 적용

2024-11-28 03:37 UTC, sangohkim commented on lib/widgets/refresh_indicator.dart
> +const indicatorRadius = 15.0; // 원의 default radius
Flutter에서 사용하는 기본값(_kDefaultIndicatorRadius) 10.0으로 변경 부탁드립니다

2024-11-28 03:40 UTC, sangohkim requested changes
RefreshIndicator radius 관련한 간단한 수정 요청 드렸습니다. 시뮬레이터에서 본 결과 전체적으로 잘 동작하는것 같습니다! 안드로이드에서는 CustomRefreshIndicator만 cupertino 스타일이고 나머지는 material 디자인에 맞춰져있어서 부자연스러울 수도 있겠다는 생각이 드는데 CustomRefreshIndicator를 iOS 일 때만 적용해보는건 어떠신가요?

2025-02-19 10:26 UTC, sangohkim requested changes
<img width="951" alt="image" src="https://github.com/user-attachments/assets/1b060176-279f-495a-bc9f-2e090d4f286e" />

```flutter run``하고 나서 홈화면으로 들어가면 위 에러가 발생하여 수정 요청드립니다.
기종은 iphone 16 (iOS 18.1), Pixel (Android API 34) 입니다

2025-04-22 10:05 UTC, sparcscasio approved these changes
LGTM,, 늦게 확인해서 죄송합니다ㅜㅠㅜㅠ

2025-04-22 10:18 UTC, thomaskim1130 reviewed
해결했습니다

2025-04-23 13:41 UTC, sangohkim approved these changes
LGTM

2025-04-29 10:42 UTC, merged