Feature/webview renewal
sparcs-kaist/new-ara-app pull request #3
Opened 2023-05-02 18:32 UTC by skykhs3

1. WebView 위젯을 이용하여 sparcsSSO 를 통해 앱 로그인이 가능합니다.
sparcs 테스트 계정을 사용하면 됩니다.
2. api/me로 사용자 계정 정보를 불러왔습니다. UserPage에서 확인 가능합니다.
3. 전반적으로 refactoring 했습니다. 클래스, 위젯, 프로바이더 이름들 수정했고, 정리했습니다.

Pull Request 할 사이즈가 더 커지기 전에 한 번 Pull Request 하겠습니다.

2023-05-06 12:06 UTC, sboh1214 requested changes
전체적으로 `flutter analyze` 돌려서 해결해 주세요

2023-05-06 12:06 UTC, sboh1214 commented on lib/pages/user_page.dart
> +                              "${context.watch<UserProvider>().naUser!.sso_user_info['first_name']} ${context.watch<UserProvider>().naUser!.sso_user_info['last_name']}",
var naUser = context.watch<UserProvider>().naUser 로 한번 정의해 주면 성능과 가독성에 도움이 될 것 같습니다

2023-05-11 12:52 UTC, sangohkim commented on lib/models/nauser_model.dart
> +  final bool is_official;
nauser_model.dart에 있는 변수명은 뉴아라 백엔드에서 사용하던 변수명과 동일하게 구성하여 그대로 두는 것이 코드 이해에 편리할 것 같습니다.

2023-05-11 13:56 UTC, skykhs3 commented on .gitignore
> +/macos/
해결 완료

2023-05-11 13:57 UTC, skykhs3 commented on android/app/build.gradle
> +        minSdkVersion 23
버전 복귀 완료

2023-05-11 13:58 UTC, skykhs3 commented on lib/dio_info.dart
> +  var _dio = Dio();
dio_info.dart 삭제

2023-05-11 18:36 UTC, skykhs3 commented
> 전체적으로 `flutter analyze` 돌려서 해결해 주세요

flutter analyze로 해결했습니다.

2023-05-13 18:02 UTC, sboh1214 approved these changes

2023-05-14 07:22 UTC, merged