숨겨진 글 표시하도록 변경 및 제목, 색상 설정
sparcs-kaist/new-ara-app pull request #41
Opened 2024-01-24 13:17 UTC by sangohkim

UserPage, UserViewPage, PostListShowPage, MainPage에서 숨겨진 글이 '차단한 사용자의 게시물입니다.' 또는 '숨겨진 게시물입니다.'로 표기되도록 변경하였습니다. 색상 또한 회색으로 변경하였습니다.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-24 at 22 12 39](https://github.com/sparcs-kaist/new-ara-app/assets/48672097/bab8ad7f-f4b0-489f-93ad-77414f03958d)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-24 at 22 12 45](https://github.com/sparcs-kaist/new-ara-app/assets/48672097/49290896-f43c-462f-9118-1ebb651f9d02)

2024-01-30 12:26 UTC, skykhs3 commented on lib/pages/post_list_show_page.dart
> -                              );
원래 숨겨진 글이면 클릭이 불가능한건데, 숨겨진 글도 클릭이 가능해진다면 오류가 발생하지 않을까요?

2024-01-30 12:31 UTC, skykhs3 requested changes

2024-01-30 12:31 UTC, skykhs3 commented on lib/utils/get_title.dart
>    }
기준을 마지막 원소에서 첫 번째 원소로 바꾼 이유가 뭔가요?

2024-01-30 13:33 UTC, sangohkim commented on lib/utils/get_title.dart
>    }
뉴아라웹에서 첫 번째 원소를 기준으로 표시하는 것 같아서 맞추느라 바꾸었습니다.

2024-02-01 05:08 UTC, sangohkim commented on lib/pages/post_list_show_page.dart
> +                        );
숨겨진 글(is_hidden=true)인 경우에 글 클릭은 가능하지만 PostViewPage에 들어갔을 때 모델 정보의 is_hidden, can_override_hidden(숨겨진 글이지만 원한다면 볼 수 있는지 여부. 웹에서 '숨김 내용 보기' 버튼 기능을 보시면 잘 이해되실 겁니다), why_hidden (숨겨진 사유.) 값을 바탕으로 글이 가려지게 됩니다.
아라에서는 is_hidden=true인 숨겨진 글이라도 클릭해서 접속은 가능하지만 can_override_hidden을 바탕으로 내용을 확인할 수 있는지 여부를 나타내므로 이 부분에서 오류가 발생하지는 않습니다.

2024-02-01 05:19 UTC, sangohkim commented
리뷰해주신 부분 바탕으로 오류가 발생하지 않는지 확인하였고 리팩토링을 진행했습니다.

2024-02-01 17:11 UTC, skykhs3 commented on lib/utils/handle_hidden.dart
> +  // 숨겨진 글이 아닌 경우
숨겨진 글이 아니라 숨겨진 게시물이라고 해주세요.
글이랑 게시물 표현 구분 해야할 것 같습니다.

2024-02-01 17:12 UTC, skykhs3 commented on lib/utils/handle_hidden.dart
> +}
주석에 글, 게시물, 댓글 표현 구분해서 주석 작성하는건 어떠신가요?
처음 보는 사진 입장에서는 글이 게시물을 의미하는 건지 파악하기 어려울 것 같아요.

2024-02-01 17:14 UTC, skykhs3 commented on lib/utils/handle_hidden.dart
> +/// 사용자에게 숨겨진 글에 대한 처리 방법을 알려주는 함수.
사용자에게 숨겨진 댓글에 대한 처리 방침을 알려주는 함수 인가요?

2024-02-01 17:16 UTC, skykhs3 commented on lib/pages/post_view_page.dart
>  }
handle_hidden.dart에 있는 함수와 이름이 겹칩니다. 기능 상으로 두 함수가 차이가 있는 건가요?

2024-02-01 17:18 UTC, skykhs3 commented on lib/utils/handle_hidden.dart
> +};
바꾸고 싶은데 뭔가 더 좋은 방법이 생각이 안나네요. 변수 앞에 const 달아주세용

2024-02-01 17:30 UTC, skykhs3 requested changes

2024-02-01 17:30 UTC, skykhs3 commented on lib/pages/user_page.dart
> +                                          curPost.comment_count! > 0)),
```
Widget _buildIcons() {
    List widgets = [];
    if (widget.model.positive_vote_count != 0) {
      widgets.add(
        Row(
          children: [
            SvgPicture.asset(
              'assets/icons/like.svg',
              width: 20,
              height: 20,
              colorFilter:
                  const ColorFilter.mode(Color(0xFFED3A3A), BlendMode.srcIn),
            ),
            Text(
              widget.model.positive_vote_count.toString(),
              style: const TextStyle(
                fontWeight: FontWeight.w500,
                fontSize: 12,
                color: Color(0xFFED3A3A),
              ),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      );
    }
    if (widget.model.negative_vote_count != 0) {
      if (widgets.isNotEmpty) {
        widgets.add(const SizedBox(
          width: 8,
        ));
      }
      widgets.add(
        Row(
          children: [
            SvgPicture.asset('assets/icons/dislike.svg',
                width: 20,
                height: 20,
                colorFilter:
                    const ColorFilter.mode(Color(0xFF538DD1), BlendMode.srcIn)),
            Text(
              widget.model.negative_vote_count.toString(),
              style: const TextStyle(
                  fontWeight: FontWeight.w500,
                  fontSize: 12,
                  color: Color(0xFF538DD1)),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      );
    }
    if (widget.model.comment_count != 0) {
      if (widgets.isNotEmpty) {
        widgets.add(const SizedBox(
          width: 8,
        ));
      }
      widgets.add(
        Row(
          children: [
            SvgPicture.asset('assets/icons/comment.svg',
                width: 20,
                height: 20,
                colorFilter:
                    const ColorFilter.mode(Color(0xFF636363), BlendMode.srcIn)),
            Text(
              widget.model.comment_count.toString(),
              style: const TextStyle(
                fontWeight: FontWeight.w500,
                fontSize: 12,
                color: Color(0xFF636363),
              ),
            ),
          ],
        ),
      );
    }
    return Row(
      children: [
        ...widgets,
      ],
    );
  }
}
```
 전 그냥 함수로 빼서 만들었어요.
widgets/post_preview.dart 파일도 있지 않나요?

2024-02-01 17:34 UTC, skykhs3 requested changes
나중에 Merge 할 때, 로컬 design/show-hidden-post 브랜치에서 "git merge origin/dev" 해서 vscode에서 충돌난거 처리하고, 실행 되는 지 확인해서 commit 다시 해주세요.

2024-02-02 06:50 UTC, sangohkim commented on lib/pages/post_view_page.dart
>  }
아닙니다. 미처 제거하지 못했었네요. PostViewPage에서는 제거하겠습니다.

2024-02-02 13:12 UTC, sangohkim commented on lib/utils/handle_hidden.dart
> +};
const 추가 완료했습니다.

2024-02-02 13:24 UTC, sangohkim commented on lib/utils/handle_hidden.dart
> +/// 사용자에게 숨겨진 글에 대한 처리 방법을 알려주는 함수.
함수 설명을 본래 목적에 맞게 변경하여놓았습니다.

2024-02-02 13:24 UTC, sangohkim commented on lib/pages/user_page.dart
> +                                          curPost.comment_count! > 0)),
TODO 태스크 처리해두고 1차 출시 이후에 작업헤보도록 하겠습니다.

2024-02-02 13:40 UTC, skykhs3 approved these changes

2024-02-02 15:27 UTC, merged