포탈 공지글 북마크 추가
sparcs-kaist/new-ara-app pull request #68
Opened 2024-02-04 09:54 UTC by sangohkim

PostViewPage에서 포탈 공지글일 경우 웹과 동일하게 북마크를 보여주도록 했습니다.
## 북마크 사진
<img width="434" alt="image" src="https://github.com/sparcs-kaist/new-ara-app/assets/48672097/8ede833b-10c7-4fef-9127-fe8f8dfa251b">

## 링크열기에 실패했을 때는 아래와 같은 화면이 표시됨
![](https://files.slack.com/files-pri/T024SHLFD-F06H0JBE92R/screenshot_20240204_184537.jpg)

2024-02-04 11:41 UTC, skykhs3 requested changes

2024-02-04 11:41 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +  }
in_article_web_view.dart에 있는 lanchInBrowser 함수랑 다른 점이 뭔가요?
주석으로 기능도 적어주면 좋을 것 같아요!

2024-02-04 13:53 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +  }
in_article_web_view.dart의 launchInBrowser는 추후 mailto 등의 scheme을 지원하게 되면 https, http이외의 scheme을 처리해야 할 수도 있어서 post_view_page.dart의 launchInBrowser와 차이가 생길 수 있습니다. 이를 염두해서 우선 따로 작성해두긴 하였는데 TODO로 통합 관련 주석처리해놓겠습니다.
함수 기능 주석 추가 완료하였습니다.

2024-02-05 02:58 UTC, skykhs3 approved these changes

2024-02-05 03:36 UTC, merged