Hotfix/api get headers
sparcs-kaist/new-ara-app pull request #76
Opened 2024-02-07 14:14 UTC by skykhs3

Feat(user_provider.dart): get과 post를 위한 createDioWithHeaders 분리
Fix(user_provider.dart): dev서버에서 csrfToken 안드로이드 문제 해결
Fix(main_page.dart): 불러온 게시물의 갯수가 표시할 게시물 갯수보다 적을 때 공백 출력하도록 수정

2024-02-08 04:51 UTC, sangohkim commented on ios/Podfile
> +    end
혹시 iOS 버전이 12 이상이어야 하는 이유가 있나요?

2024-02-08 04:54 UTC, sangohkim commented on lib/providers/user_provider.dart
> +  Dio createDioWithHeadersForPost() {
GET을 제외한 요청에서 모두 사용되는 것이니 ForPost보다는 createDiowithHeadersNonGet 과 같은 명칭이 좋을 것 같습니다. 명칭 변경이 다른 태스크 진행에 영향을 주신다면 TODO 주석만 추가해주셔도 좋고 혹시 빠르게 가능하시다면 수정 부탁드립니다.

2024-02-08 05:11 UTC, sangohkim commented on lib/providers/user_provider.dart
> +  Dio createDioWithHeadersForPost() {
추가로 createDioWithHeadersForGet, createDioWithHeadersForPost로 분리한 이유도 간단히 주석으로 추가해주시면 좋을 것 같습니다.

2024-02-08 05:12 UTC, sangohkim requested changes
리뷰완료하였습니다.

2024-02-08 13:55 UTC, skykhs3 commented on ios/Podfile
> +    end
삭제했습니다.

2024-02-09 02:20 UTC, sangohkim approved these changes
LGTM

2024-02-09 04:42 UTC, merged