Feature/comment and documentation sangohkim
sparcs-kaist/new-ara-app pull request #8
Opened 2023-09-21 15:01 UTC by sangohkim

아래 해당하는 파일에 코드의 원활한 해석을 위한 주석을 추가함.
/providers

- notification_provider.dart

/pages
- notification_page.dart
- post_view_page.dart
- setting_page.dart
- user_page.dart
- user_view_page.dart

/utils
- post_view_utils.dart

2023-10-03 12:53 UTC, skykhs3 commented on lib/providers/notification_provider.dart
> +            break;
읽지 않은 데이터가 있다는 것을 확인 했을 때 for 문만 브레이크를 걸 것이 아니라 효율성을 위해 do while에도 break를 걸 것

2023-10-03 13:19 UTC, skykhs3 commented on lib/pages/notification_page.dart
> +                                  if (mounted) {
프론트에서 미리 바꾸고, 백엔드에서 처리 받아서 다시 업데이트 다시 한 번 싹하는 코드 좋아요

2023-10-03 13:21 UTC, skykhs3 commented on lib/pages/notification_page.dart
> +  void _listViewListener() async {
비동기화 함수하는 것을 나타내기 위해 void 대신 Future<void>는 어떨까요?

2023-10-03 13:27 UTC, skykhs3 commented on lib/pages/notification_page.dart
> +                                  await notificationProvider.checkIsNotReadExist();
이 메소드를 여기서 호출하는 이유가 궁금합니다.

2023-10-03 13:30 UTC, skykhs3 commented on lib/pages/notification_page.dart
> +          await notificationProvider.checkIsNotReadExist();
checkIsNotReadExist() 메소드를 여기서 호출하는 이유가 궁금합니다.

2023-10-03 13:34 UTC, skykhs3 commented on lib/pages/notification_page.dart
> +          if (!res) {
return을 사용하는 구현 방식에 대해 고민 중입니다. return을 사용해 함수를 끝내는 대신 대신 밑에 있는 코드들을 else로 넣으면 좋지 않을까요? 의견 부탁드립니다.

2023-10-03 13:51 UTC, skykhs3 commented on lib/pages/user_page.dart
> +  void _scrollListener0() async {
_scrollListener0,1,2 세 개 함수 하나의 함수도 통합해서 만드는 건 어떨까요?

2023-10-03 13:59 UTC, skykhs3 commented on lib/pages/user_page.dart
> +                        }, // 추후에 프로필 수정 기능 구현 예정
TODO 주석으로 내용 수정 부탁드립니다.
현재 프로필 수정 기능 완료된 거 아닌가요?

2023-10-03 14:02 UTC, skykhs3 commented on lib/pages/user_page.dart
>    void setMyCount(int value, int tabIndex) {
현재 안 쓰이는 함수인 것 같습니다.

2023-10-03 14:03 UTC, skykhs3 commented on lib/pages/user_page.dart
> +  void setCurCount(int tabIndex) {
setIsLoaded, SetMyCount, SetCurCount가 어디에 사용하기 위해 만든 함수이고, 어디에 쓰이는 지 주석 설명이 있으면 좋을 것 같습니다.

2023-10-03 14:29 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +    return Stack(
굳이 Stack을 사용한 이유를 모르겠습니다.
Stack 안에 Scaffold랑 Visibility 위젯 두 가지가 있는 걸로 보입니다.
 !_isValid || !_context.watch<UserProvider>().isWebViewLoaded ? const LoadingIndicator() : Scaffold(
이런 식으로 작성하면 안될까요?

2023-10-03 14:44 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +                child: Column(children: [
가독성이 너무 떨어지는데 크게 네 가지 부분으로 나눌 필요가 있다고 생각합니다.
1. 제목, 글쓴이 이름 등: header 위젯
2. 본문: body 위젯
3. 댓글:comment 위젯
4. 댓글 작성창 : comment_write 위젯
build 함수 안에 이런 식으로 작성해서 분리하는 거 어떠신가요..?
` Widget PostBody() {
      return Container();
    }`

2023-10-03 15:11 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +  WebViewController _webViewController = WebViewController();
```
late WebViewController _webViewController;
```

이렇게 하는거 어떠신가요?

2023-10-03 15:12 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +  /// if (targetUrl.authority == newAraAuthority) {
쓸모 없는 주석 정리 부탁드립니다.

2023-10-03 15:25 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +              => userProvider.setIsWebViewLoaded(true)
여러 웹뷰를 동시에 사용하는 데 setIsWebViewLoaded 하나 가지고 상태 관리가 가능한가요?

2023-10-03 16:31 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +                                            Visibility(
이것도 무엇으 위한 위젯인지 이해가 어렵습니다. 주석 달아주시면 감사할 것 같습니다.

2023-10-03 16:34 UTC, skykhs3 commented on lib/pages/post_view_page.dart
> +                                _isReportable ? InkWell(
위젯트리 안에서 조건문(collection if)을 쓸 수 있습니다. 긴 코드는 삼항 연산자 대신 조건문을 쓰는 게 가독성이 더 높다고 생각하는 데 어떻게 생각하시나요?
예시 코드
```
Widget build(BuildContext context) {
  bool showText = true;

  return Column(
    children: [
      if (showText)
        Text('This is visible')
      else
        Text('This is hidden'),
    ],
  );
}

```

2023-10-03 16:36 UTC, skykhs3 commented
전반적으로 함수 위치에 대해 정리가 필요한 것 같습니다. initState에 쓰이는 함수들은 initState 위로 올리고, onTap 안의 익명함수, 위젯을 생성하는 함수 _buildLikeButton() , 등등 가독성 항샹을 위해 코드 내 위치 재조정이 필요한 것 같습니다.

2023-10-03 16:38 UTC, skykhs3 requested changes
1. 전반적으로 함수 위치에 대해 정리가 필요한 것 같습니다. initState에 쓰이는 함수들은 initState 위로 올리고, onTap 안의 익명함수, 위젯을 생성하는 함수 _buildLikeButton() , 등등 가독성 항샹을 위해 코드 내 위치 재조정이 필요한 것 같습니다.
2. 삼항 연산자가 너무 많아서 가독성이 떨어집니다. 조건문으로 바꾸는 거 어떻게 생각하시나요?
3. 코드 겹치는 부분에 대해서 전반적으로 리팩토링 부탁드립니다.

2023-10-05 03:39 UTC, sangohkim commented on lib/providers/notification_provider.dart
> +            break;
아주 좋습니다! TODO로 작성해두도록 하겠습니다.

2023-10-05 03:40 UTC, sangohkim commented on lib/pages/notification_page.dart
> +    _curPage = 1;
_initNotificationPage 메서드는 initState 및 페이지 새로고침 시에도 사용되는 메서드로 설계되었습니다. 그래서 페이지를 새로고침하는 상황을 위해 추가하였습니다.

2023-10-05 03:42 UTC, sangohkim commented on lib/pages/notification_page.dart
> +  void update() {
넵. updateState로 변경하겠습니다. 마찬가지로 일단은 TODO로 주석 달아놓겠습니다.

2023-10-05 03:45 UTC, sangohkim commented on lib/pages/notification_page.dart
> +      // (2023.09.23) 추후 디자이너와 조율해야함.
TODO 주석으로 변경하였습니다.

2023-10-05 03:47 UTC, sangohkim commented on lib/pages/notification_page.dart
> +                                  if (mounted) {
네 맞습니다. 사용자가 PostViewPage에서 돌아왔을 때
1. 프론트에서만 클릭한 알림 읽음처리
2. 백엔드에서 알림 읽음 처리
3. 백엔드 처리가 실패할 경우 프론트도 다시 안읽음으로 전환
4. 전체적으로 새로운 알림 조회
와 같은 과정입니다.

2023-10-05 03:50 UTC, sangohkim commented on lib/pages/notification_page.dart
> +                                  await notificationProvider.checkIsNotReadExist();
해당 코드 시점은 사용자가 NotificationPage에서 PostViewPage로 이동하였다가 다시 NotificationPage로 돌아온 경우입니다. 따라서 그 사이에 새로운 알림이 추가되었을 수 있으므로 checkIsNotReadExist()를 호출하였습니다.

2023-10-05 04:01 UTC, sangohkim commented on lib/pages/notification_page.dart
> +          await notificationProvider.checkIsNotReadExist();
현재 앱에서는 읽지 않은 알림이 있을 때 BottomNavigationBar의 알림 아이콘에 표시를 합니다.
```
Visibility(
                visible: context.watch<NotificationProvider>().isNotReadExist,
                child: Positioned(
                  top: 0,
                  right: 5,
                  child: Container(
                    width: 7,
                    height: 7,
                    decoration: const BoxDecoration(
                      shape: BoxShape.circle,
                      color: ColorsInfo.newara,
                    ),
                  ),
                ),
              ),
```
위 Visibility 위젯에서 NotificationProvider의 isNotReadExist 변수의 값을 구독하고 있습니다. isNotReadExist의 값은 checkIsNotReadExist에 의해 업데이트되므로 checkIsNotReadExist를 호출하였습니다. 그러나 다시 생각해보니 NotificaitonProvider에 isNotReadExist를 변경할 수 있는 메서드를 추가하는 것이 더 효율적일 것 같습니다. 마찬가지고 TODO로 해당 작업 추가해놓겠습니다.
그러나 지금 확인해보니 NotificationProvider

2023-10-05 04:08 UTC, sangohkim commented on lib/pages/notification_page.dart
> +          if (!res) {
넵 저도 위와 같이 처리하고 return은 마지막에 한번만 하는 것이 더 좋을 것 같습니다. 기존에 위와 같이 구현된 부분들 확인하고 많이 없다면 추후에 일괄 수정을 하고 너무 많다면 앞으로의 코드 컨벤션으로 반영하도록 하겠습니다.

2023-10-05 04:20 UTC, sangohkim commented on lib/pages/user_page.dart
> +  void _scrollListener0() async {
3가지의 리스트뷰(작성한 글, 담아둔 글, 최근 본 글)를 동일한 리스너가 모두 구독하고 있는 경우 리스너에서 3가지 중 어떤 리스트뷰에 변화가 일어났는지 감지할 수 없습니다. 그래서 리스너를 하나만 사용하는 것은 힘들 것 같지만 아래와 같은 변경은 가능할 것 같습니다.
'''
void _scrollListener0() { listener(0) }
void _scrollListener1() { listener(1) }
void _scrollListener2() { listener(2) }
void listener() {
    위 리스너에서 겹치는 작업들을 메서드화
}
'''
위와 같은 통합방식에 대해 어떻게 생각하시나요?

2023-10-05 04:22 UTC, sangohkim commented on lib/pages/user_page.dart
> +                        }, // 추후에 프로필 수정 기능 구현 예정
넵! 미처 제거하지 못한 것 같습니다. 주석 관련한 처리이니 이 브랜치에서 바로 제거하도록 하겠습니다.

2023-10-05 04:24 UTC, sangohkim commented on lib/pages/user_page.dart
>    void setMyCount(int value, int tabIndex) {
넵 예전에 리팩토링하면서 더 이상 사용하지 않게 된 것 같습니다. TODO로 해당 작업 기록해놓았습니다.

2023-10-05 04:29 UTC, sangohkim commented on lib/pages/user_page.dart
> +  void setCurCount(int tabIndex) {
setIsLoaded, setCurCount에 대한 주석 처리 완료하였습니다. setMyCount는 더이상 사용되지 않아 추가하지 않았습니다.

2023-10-05 04:29 UTC, sangohkim commented on lib/pages/user_page.dart
> +  Future<bool> fetchScrappedArticles(UserProvider userProvider, int page) async {
정말 좋습니다! TODO로 기록해놓겠습니다.

2023-10-05 04:40 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +            const Duration(milliseconds: 500), ()
웹뷰의 height 조절이 끝나고 웹뷰가 변경된 height에 맞춰 리로드되는데에 시간이 걸려 그렇습니다. 해당 시간은 임시적으로 설정한 거라 추후에 다시 고려하겠습니다.

2023-10-05 04:45 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +  WebViewController _webViewController = WebViewController();
좋은 것 같습니다! TODO로 추가하겠습니다.

2023-10-05 13:32 UTC, sangohkim commented on lib/utils/post_view_utils.dart
> +  void _setVote(bool value) {
```
model.negative_vote_count ??=0
```
과 같은 경우는 제가 미처 넣지 못했던 것 같습니다. 간단한 코드이니 TODO하지 않고 바로 추가하겠습니다.

value 파라미터의 의미 및 각각의 코드에 대한 주석 설명을 추가하였습니다.

2023-10-05 13:34 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +  void update() {
updateState로 수정하는거 어떠신가요? 우선 TODO 처리해놓겠습니다.

2023-10-05 13:38 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +                                            Visibility(
주석 설명 추가 완료하였습니다.

2023-10-05 13:38 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +                                            Visibility(
주석 추가 완료하였습니다.

2023-10-05 13:41 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +                                _isReportable ? InkWell(
좋습니다. 삼항연산자보다 더 가독성을 높힐 수 있을 것 같습니다. TODO로 처리해놓겠습니다.

2023-10-05 13:57 UTC, sangohkim commented on lib/pages/post_view_page.dart
> +              => userProvider.setIsWebViewLoaded(true)
미처 놓친 부분이네요.......TODO로 추가하고 가장 우선으로 수정하겠습니다.

2023-10-05 15:02 UTC, skykhs3 approved these changes

2023-10-05 15:02 UTC, merged