Feat/add boards on main page
sparcs-kaist/new-ara-app pull request #80
Opened 2024-02-08 18:38 UTC by skykhs3

2024-02-09 07:55 UTC, skykhs3 commented on lib/pages/main_page.dart
> +                              boardNum: 1,
필드명 변경

2024-02-09 07:56 UTC, skykhs3 commented on lib/pages/main_page.dart
> +      this.showBoardNumber = true});
ingiNum에서 boardNum으로 매개변수 이름 변경

2024-02-11 04:40 UTC, sangohkim requested changes
우선 추가된 자유게시판 디자인 좋은 것 같습니다. 한 가지 제안드려보고 싶은 부분이 아라에서 거래(구인구직, 중고거래, 부동산) 게시판도 많으 쓰이는 편이니까 
<img width="421" alt="image" src="https://github.com/sparcs-kaist/new-ara-app/assets/48672097/c07e630e-8318-45c1-9404-2dbb62a5bee8">
위처럼 거래 게시판 내용도 구인구직 중심으로 추가해보는거 어떠신가요?

2024-02-13 03:39 UTC, sangohkim approved these changes
LGTM

2024-02-13 04:14 UTC, merged